//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Language", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        internal static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We help suppliers, importers and wholesalers showcase their products to buyers who are looking for great deals on wholesale beauty products..
        /// </summary>
        internal static string AboutUsCheckContent1 {
            get {
                return ResourceManager.GetString("AboutUsCheckContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our sellers are ready to ship out their items directly to you. Plus we help you clean up with our quick and painless selling services..
        /// </summary>
        internal static string AboutUsCheckContent2 {
            get {
                return ResourceManager.GetString("AboutUsCheckContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our network has been designed to help you find suppliers efficiently and to keep up to date with the latest developments in the industry..
        /// </summary>
        internal static string AboutUsCheckContent3 {
            get {
                return ResourceManager.GetString("AboutUsCheckContent3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We make finding suppliers a pleasant experience so you can spend more time improving your business..
        /// </summary>
        internal static string AboutUsCheckContent4 {
            get {
                return ResourceManager.GetString("AboutUsCheckContent4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaan Marketplace is a one-stop shop for salon and spa supplies. Our goal is to make your life easier by helping you find what you need, giving you great advice on how to use it, then
        ///shipping it to you quickly and efficiently. We are a young company, built by like-minded
        ///professionals who love what they do, and we&apos;re excited to help our customers find the
        ///products they need in one convenient place..
        /// </summary>
        internal static string AboutUsContent1 {
            get {
                return ResourceManager.GetString("AboutUsContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We strive to be the best online platform for beauty industry suppliers by committing
        ///ourselves to provide a selected, qualified and high quality set of suppliers to our customers
        ///in a trusted environment..
        /// </summary>
        internal static string AboutUsContent2 {
            get {
                return ResourceManager.GetString("AboutUsContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All-IN-ONE software management to manage and grow your salon and spa business ..
        /// </summary>
        internal static string AllInOne {
            get {
                return ResourceManager.GetString("AllInOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Services.
        /// </summary>
        internal static string AllServices {
            get {
                return ResourceManager.GetString("AllServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        internal static string Alreadyhaveanaccount {
            get {
                return ResourceManager.GetString("Alreadyhaveanaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always focus on your growth, and let the innovation for us..
        /// </summary>
        internal static string Alwaysfocus {
            get {
                return ResourceManager.GetString("Alwaysfocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any time.
        /// </summary>
        internal static string Anytime {
            get {
                return ResourceManager.GetString("Anytime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointments.
        /// </summary>
        internal static string Appointments {
            get {
                return ResourceManager.GetString("Appointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fast and easy-to-use appointment book for front desk staff is just the start of our omnichannel booking experiences. Provide your guests (and staff) with the ease and convenience they expect..
        /// </summary>
        internal static string AppointmentsContent {
            get {
                return ResourceManager.GetString("AppointmentsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ar.
        /// </summary>
        internal static string Ar {
            get {
                return ResourceManager.GetString("Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beauty Salon.
        /// </summary>
        internal static string BeautySalon {
            get {
                return ResourceManager.GetString("BeautySalon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        internal static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches Management.
        /// </summary>
        internal static string Branchesmanagement {
            get {
                return ResourceManager.GetString("Branchesmanagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open an unlimited number of branches for your business and follow them all from one place.
        /// </summary>
        internal static string BranchesmanagementContent {
            get {
                return ResourceManager.GetString("BranchesmanagementContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Now.
        /// </summary>
        internal static string BuyNow {
            get {
                return ResourceManager.GetString("BuyNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditioner.
        /// </summary>
        internal static string Conditioner {
            get {
                return ResourceManager.GetString("Conditioner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents.
        /// </summary>
        internal static string Contents {
            get {
                return ResourceManager.GetString("Contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ©Copyright Zaan 2022. All rights reserved..
        /// </summary>
        internal static string CopyrightZaan {
            get {
                return ResourceManager.GetString("CopyrightZaan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Management.
        /// </summary>
        internal static string Customermanagement {
            get {
                return ResourceManager.GetString("Customermanagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Zaan you can manage your customers&apos; records in a wonderful way, as you can track their last visit and know some of the details that interest you about them with simple tools..
        /// </summary>
        internal static string CustomermanagementContent {
            get {
                return ResourceManager.GetString("CustomermanagementContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahra Ahmad.
        /// </summary>
        internal static string CustomerTestimonialBy1 {
            get {
                return ResourceManager.GetString("CustomerTestimonialBy1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mashael Algahtani.
        /// </summary>
        internal static string CustomerTestimonialBy2 {
            get {
                return ResourceManager.GetString("CustomerTestimonialBy2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Murad Alinezi.
        /// </summary>
        internal static string CustomerTestimonialBy3 {
            get {
                return ResourceManager.GetString("CustomerTestimonialBy3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Murad Alinezi.
        /// </summary>
        internal static string CustomerTestimonialBy4 {
            get {
                return ResourceManager.GetString("CustomerTestimonialBy4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am so glad I found Zaan Marketplace before I wasted my time and money on other
        ///marketplaces..
        /// </summary>
        internal static string CustomerTestimonialContent1 {
            get {
                return ResourceManager.GetString("CustomerTestimonialContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi there, Zaan has helped me reach out to a larger audience, I get a lot of views and
        ///sales here. It took some time to figure out how to use the tools but they are very
        ///helpful. So far so good!.
        /// </summary>
        internal static string CustomerTestimonialContent2 {
            get {
                return ResourceManager.GetString("CustomerTestimonialContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re a very small company with a lot of private branded products. Zaan has helped
        ///us to sell our products in a bigger scale than before..
        /// </summary>
        internal static string CustomerTestimonialContent3 {
            get {
                return ResourceManager.GetString("CustomerTestimonialContent3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re a very small company with a lot of private branded products. Zaan has helped
        ///us to sell our products in a bigger scale than before..
        /// </summary>
        internal static string CustomerTestimonialContent4 {
            get {
                return ResourceManager.GetString("CustomerTestimonialContent4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull data from every aspect of your business, including sales, operations, marketing, staff performance and customer behavior..
        /// </summary>
        internal static string DashboardContent1 {
            get {
                return ResourceManager.GetString("DashboardContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ll always have access to dashboard that are up-to-date and accurate, without the manual effort to collate your data outside of the system..
        /// </summary>
        internal static string DashboardContent2 {
            get {
                return ResourceManager.GetString("DashboardContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DREOX HAIR DRYER, 2000W AC.
        /// </summary>
        internal static string DREOXHAIRDRYER {
            get {
                return ResourceManager.GetString("DREOXHAIRDRYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During the day.
        /// </summary>
        internal static string Duringtheday {
            get {
                return ResourceManager.GetString("Duringtheday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During the Night.
        /// </summary>
        internal static string DuringtheNight {
            get {
                return ResourceManager.GetString("DuringtheNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        internal static string Emailisrequired {
            get {
                return ResourceManager.GetString("Emailisrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email.
        /// </summary>
        internal static string EmailValidationMessage {
            get {
                return ResourceManager.GetString("EmailValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facial Steamer.
        /// </summary>
        internal static string FacialSteamer {
            get {
                return ResourceManager.GetString("FacialSteamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Us.
        /// </summary>
        internal static string FollowUs {
            get {
                return ResourceManager.GetString("FollowUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaan salon software delivers everything you need for your salon and spa to optimize scheduling appointments, employee management, customer management, marketing, inventory, and much more...
        /// </summary>
        internal static string footerContent {
            get {
                return ResourceManager.GetString("footerContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Consultation.
        /// </summary>
        internal static string FreeConsultation {
            get {
                return ResourceManager.GetString("FreeConsultation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get A Consultant.
        /// </summary>
        internal static string GetAConsultant {
            get {
                return ResourceManager.GetString("GetAConsultant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get An Invoice.
        /// </summary>
        internal static string GetAnInvoice {
            get {
                return ResourceManager.GetString("GetAnInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get More Update.
        /// </summary>
        internal static string GetMoreUpdate {
            get {
                return ResourceManager.GetString("GetMoreUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        internal static string GetStarted {
            get {
                return ResourceManager.GetString("GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gloves.
        /// </summary>
        internal static string Gloves {
            get {
                return ResourceManager.GetString("Gloves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat Protecting Smoothing Spray.
        /// </summary>
        internal static string HeatProtectingSmoothingSpray {
            get {
                return ResourceManager.GetString("HeatProtectingSmoothingSpray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat Protection Spray.
        /// </summary>
        internal static string HeatProtectionSpray {
            get {
                return ResourceManager.GetString("HeatProtectionSpray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight Brush.
        /// </summary>
        internal static string HighlightBrush {
            get {
                return ResourceManager.GetString("HighlightBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        internal static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A program that helps you control your inventory..
        /// </summary>
        internal static string InventoryContent1 {
            get {
                return ResourceManager.GetString("InventoryContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streamline processes to manage inventory more efficiently. It&apos;s easy to withdraw and add to your products..
        /// </summary>
        internal static string InventoryContent2 {
            get {
                return ResourceManager.GetString("InventoryContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Know when to reorder.
        /// </summary>
        internal static string InventoryContent3 {
            get {
                return ResourceManager.GetString("InventoryContent3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alerts warn you when stock is running low..
        /// </summary>
        internal static string InventoryContent4 {
            get {
                return ResourceManager.GetString("InventoryContent4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find product suppliers that are intelligently integrated within the inventory, Keep track of your inventory products and lists of suppliers..
        /// </summary>
        internal static string InventoryContent5 {
            get {
                return ResourceManager.GetString("InventoryContent5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaan allows you to issue E- invoices in accordance with the requirements of the General Authority of Zakat and Income for the electronic invoice system, where you can issue your invoices with approved forms of tax invoice or simplified invoice, in addition to the program support for applicable taxes such as value-added tax and automatically included in the issued invoices, to Along with the required basic information such as the tax number of the customer, and the tax information of the institution..
        /// </summary>
        internal static string InvoiceContent {
            get {
                return ResourceManager.GetString("InvoiceContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start E- invoicing with the Zaan system approved by ZATCA.
        /// </summary>
        internal static string InvoiceTitle {
            get {
                return ResourceManager.GetString("InvoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to start as a....
        /// </summary>
        internal static string Iwantto {
            get {
                return ResourceManager.GetString("Iwantto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaan salon software delivers everything you need for your salon and spa to optimize  scheduling appointments, employee management..
        /// </summary>
        internal static string IwanttoContent {
            get {
                return ResourceManager.GetString("IwanttoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs.
        /// </summary>
        internal static string Jobs {
            get {
                return ResourceManager.GetString("Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Know More.
        /// </summary>
        internal static string KnowMore {
            get {
                return ResourceManager.GetString("KnowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing.
        /// </summary>
        internal static string Marketing {
            get {
                return ResourceManager.GetString("Marketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaan&apos;s marketing automation software is tailor-made for the salon and spa business. Our solution reduces the time and expense to plan and execute marketing programs. Most importantly, we help you grow revenue with lasting results..
        /// </summary>
        internal static string MarketingContent1 {
            get {
                return ResourceManager.GetString("MarketingContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We provide your salon with multiple options to do marketing and carefully select customers to target. From emails, text messages, offers and daily deals.
        ///Always be prepared to jump your salon sales!.
        /// </summary>
        internal static string MarketingContent2 {
            get {
                return ResourceManager.GetString("MarketingContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your name.
        /// </summary>
        internal static string NameValidationMessage {
            get {
                return ResourceManager.GetString("NameValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No setup costs or contract.
        /// </summary>
        internal static string Nosetup {
            get {
                return ResourceManager.GetString("Nosetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One stop shop.
        /// </summary>
        internal static string Onestopshop {
            get {
                return ResourceManager.GetString("Onestopshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop your salon and spa products from different suppliers from one place, compare prices, see reviews, leave your comments, Track your purchases, various payment options and more from inside Zaan&apos;s store..
        /// </summary>
        internal static string OnestopshopContent1 {
            get {
                return ResourceManager.GetString("OnestopshopContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you a supplier? Do you have your own products for beauty salons and spas?.
        /// </summary>
        internal static string OnestopshopContent2 {
            get {
                return ResourceManager.GetString("OnestopshopContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register now as a supplier and reach more customers.
        /// </summary>
        internal static string OnestopshopContent3 {
            get {
                return ResourceManager.GetString("OnestopshopContent3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Best Sell Product In This Week!.
        /// </summary>
        internal static string OurBestSell {
            get {
                return ResourceManager.GetString("OurBestSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Blog Post.
        /// </summary>
        internal static string OurBlogPost {
            get {
                return ResourceManager.GetString("OurBlogPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our
        ///Customer Says.
        /// </summary>
        internal static string OurCustomerSays {
            get {
                return ResourceManager.GetString("OurCustomerSays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our customers are the basis of our success, and they are the first motivation for us to
        ///develop and excel. We are always looking for their satisfaction and providing the best
        ///services that help them develop their business..
        /// </summary>
        internal static string OurCustomerSaysContent {
            get {
                return ResourceManager.GetString("OurCustomerSaysContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Product.
        /// </summary>
        internal static string OurProduct {
            get {
                return ResourceManager.GetString("OurProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just one click and you have access to thousands of top-quality products. We do all
        ///the hard work for you by negotiating with suppliers so you can find exactly what you
        ///need, quickly and simply..
        /// </summary>
        internal static string OurProductContent {
            get {
                return ResourceManager.GetString("OurProductContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Supplier.
        /// </summary>
        internal static string OurSupplier {
            get {
                return ResourceManager.GetString("OurSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A business is only as great as its suppliers. With the proper tools, you can make better
        ///decisions easily..
        /// </summary>
        internal static string OurSupplierContent {
            get {
                return ResourceManager.GetString("OurSupplierContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your phonenumber.
        /// </summary>
        internal static string PhoneNumberValidation {
            get {
                return ResourceManager.GetString("PhoneNumberValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Supplier.
        /// </summary>
        internal static string ProductSupplier {
            get {
                return ResourceManager.GetString("ProductSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new market here for you and your customers.
        /// </summary>
        internal static string ProductsupplierContent1 {
            get {
                return ResourceManager.GetString("ProductsupplierContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make your products reach the hands of your customers in a modern and innovative style.
        /// </summary>
        internal static string ProductsupplierContent2 {
            get {
                return ResourceManager.GetString("ProductsupplierContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Links.
        /// </summary>
        internal static string QuickLinks {
            get {
                return ResourceManager.GetString("QuickLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reach Out Time.
        /// </summary>
        internal static string ReachOutTime {
            get {
                return ResourceManager.GetString("ReachOutTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a reach out time.
        /// </summary>
        internal static string ReachOutTimeLabel {
            get {
                return ResourceManager.GetString("ReachOutTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your reach out time.
        /// </summary>
        internal static string ReachOutTimeValidation {
            get {
                return ResourceManager.GetString("ReachOutTimeValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Less.
        /// </summary>
        internal static string ReadLess {
            get {
                return ResourceManager.GetString("ReadLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read More.
        /// </summary>
        internal static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended Blogs.
        /// </summary>
        internal static string RecommendedBlogs {
            get {
                return ResourceManager.GetString("RecommendedBlogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular User.
        /// </summary>
        internal static string RegularUser {
            get {
                return ResourceManager.GetString("RegularUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request A Call.
        /// </summary>
        internal static string RequestACall {
            get {
                return ResourceManager.GetString("RequestACall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salon.
        /// </summary>
        internal static string Salon {
            get {
                return ResourceManager.GetString("Salon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salon Owner.
        /// </summary>
        internal static string SalonOwner {
            get {
                return ResourceManager.GetString("SalonOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the best management system to manage all aspects of your salon.
        /// </summary>
        internal static string SalonOwnerContent1 {
            get {
                return ResourceManager.GetString("SalonOwnerContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make your business grow with Zan experts who are interested in providing everything needed to develop your business.
        /// </summary>
        internal static string SalonOwnerContent2 {
            get {
                return ResourceManager.GetString("SalonOwnerContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule A Call.
        /// </summary>
        internal static string scheduleacall {
            get {
                return ResourceManager.GetString("scheduleacall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out Zaan&apos;s unique business model which allows small to medium-sized
        ///businesses to reach Thousands of consumers across Many countries through one
        ///platform..
        /// </summary>
        internal static string scheduleacallContent {
            get {
                return ResourceManager.GetString("scheduleacallContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Here.
        /// </summary>
        internal static string SearchHere {
            get {
                return ResourceManager.GetString("SearchHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See All.
        /// </summary>
        internal static string SeeAll {
            get {
                return ResourceManager.GetString("SeeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price: $100.
        /// </summary>
        internal static string SellProductPrice {
            get {
                return ResourceManager.GetString("SellProductPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Management.
        /// </summary>
        internal static string ServiceManagement {
            get {
                return ResourceManager.GetString("ServiceManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flexible system to list all services and any services provided by your salon. You can manage them by assigning them to employees, setting their prices and duration, as well as set them as packages and much more..
        /// </summary>
        internal static string ServiceManagementContent {
            get {
                return ResourceManager.GetString("ServiceManagementContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Article.
        /// </summary>
        internal static string ShareArticle {
            get {
                return ResourceManager.GetString("ShareArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share On.
        /// </summary>
        internal static string Shareon {
            get {
                return ResourceManager.GetString("Shareon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in here.
        /// </summary>
        internal static string Signinhere {
            get {
                return ResourceManager.GetString("Signinhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spa.
        /// </summary>
        internal static string Spa {
            get {
                return ResourceManager.GetString("Spa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Management.
        /// </summary>
        internal static string Staffmanagement {
            get {
                return ResourceManager.GetString("Staffmanagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage employee roll, performance, leave and attendance with our all-in-one spa and salon staff management software..
        /// </summary>
        internal static string StaffmanagementContent {
            get {
                return ResourceManager.GetString("StaffmanagementContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start managing your beauty salon in just few minutes.
        /// </summary>
        internal static string Startmanaging {
            get {
                return ResourceManager.GetString("Startmanaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay informed on the latest in salons and beauty products. Subscribe to our newsletter for expert tips, industry insights, new product reviews and more. Never miss a trend again, sign up now..
        /// </summary>
        internal static string Stayinformedonthelatestinsalons {
            get {
                return ResourceManager.GetString("Stayinformedonthelatestinsalons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        internal static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaan Marketplace is a platform that provides the best solution for connecting Beauty salon
        ///products manufacturers, distributors, wholesalers and service providers under one roof.
        ///With thousands of options, Zaan has every product you need to create the salon
        ///experience every customer deserves..
        /// </summary>
        internal static string StoreBannerContent1 {
            get {
                return ResourceManager.GetString("StoreBannerContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Zaan Marketplace as a seller and experience the beauty of ease, no hassle, simple yet
        ///organized.
        /// </summary>
        internal static string StoreBannerContent2 {
            get {
                return ResourceManager.GetString("StoreBannerContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beauty industry&apos;s one stop solution to grow your salon &amp; spa business.
        /// </summary>
        internal static string StoreBannerHeading {
            get {
                return ResourceManager.GetString("StoreBannerHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styling Chair.
        /// </summary>
        internal static string StylingChair {
            get {
                return ResourceManager.GetString("StylingChair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your Subject.
        /// </summary>
        internal static string SubjectValidationMessage {
            get {
                return ResourceManager.GetString("SubjectValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        internal static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe Newslatter.
        /// </summary>
        internal static string SubscribeNewslatter {
            get {
                return ResourceManager.GetString("SubscribeNewslatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; Contitions.
        /// </summary>
        internal static string TermsAndContitions {
            get {
                return ResourceManager.GetString("TermsAndContitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Articles.
        /// </summary>
        internal static string TopArticles {
            get {
                return ResourceManager.GetString("TopArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Posts.
        /// </summary>
        internal static string TopPosts {
            get {
                return ResourceManager.GetString("TopPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We design Zaan System to cover all your salon needs, to help you work beautifully.
        /// </summary>
        internal static string Wedesigned {
            get {
                return ResourceManager.GetString("Wedesigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Name.
        /// </summary>
        internal static string YourName {
            get {
                return ResourceManager.GetString("YourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your fullname.
        /// </summary>
        internal static string YourNameValidation {
            get {
                return ResourceManager.GetString("YourNameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaan salon software delivers everything you need for your salon and spa to optimize scheduling
        ///appointments, employee management, customer management, marketing, inventory, and much
        ///more...
        /// </summary>
        internal static string ZaanSalonSoftware {
            get {
                return ResourceManager.GetString("ZaanSalonSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaan salon software delivers everything you need for your salon and spa to optimize scheduling appointments, employee management, customer management, marketing, inventory, and much more...
        /// </summary>
        internal static string Zaansalonsoftwaredelivers {
            get {
                return ResourceManager.GetString("Zaansalonsoftwaredelivers", resourceCulture);
            }
        }
    }
}
